config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile
  
  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post "post/vote"  => "votes#create"

  root to: "public#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    has_many :comments
  
    validates_presence_of :title, :body, :account_id, :community_id

    def score
        if self.upvotes > 0 || self.downvotes > 0
            self.upvotes> 0 ? (self.upvotes - self.downvotes) : (self.downvotes * -1)
        else
            0
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only: [:new]


    def index
        @posts = Post.all
    end

    def show 
        @comment= Comment.new
    end

    def new 
        @community = Community.find(params[:community_id])
        @post = Post.new
    end

    def create 
        @post = Post.new post_values
        @post.account_id = current_account.id
        @post.community_id = params[:community_id]

        if @post.save
            redirect_to community_path(@post.community_id)
        else
            @community = Community.find(params[:community_id])
            render :new
        end
    end

    def auth_subscriber
         unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
            redirect_to root_path, flash: {danger: "You are not authorized to view this page" }
         end
    end

    private

    def set_post
        @post = Post.includes(:comments).find(params[:id])
    end

    def post_values
        params.require(:post).permit(:title, :body)
    end


end

app/views/posts/_comments.html.erb
<%comments.each do |comment|%>
<br   />
<div class="comment">
<%=link_to comment.account.username, profile_path(comment.account.username)%>
<%= simple_format comment.message %>
</div>
<%end%>

app/views/posts/_form.html.erb
<div class="row">
<div class="col-sm-6">

<%= form_for [@community, @post] do |form| %>
<div class="form-group">
<%= label_tag :title %>
<%= form.text_field :title, class: "form-control"%>
</div>



<div class="form-group">
<%= label_tag :body %>
<%= form.text_area :body, class: "form-control"%>
</div>

<%= form.submit "Submit", class: "btn btn-primary"%>
<% end %>
</div>
</div>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
    <br  />
    <div class="card p-3">
    <div class="row">
      <div class="col-1 text-center">
      <div id="vote-actions-<%=post.id%>" class="vote" data-id="<%=post.id%>">
      <div class ="fa fa-arrow-up upvote <%= is_upvoted post%>" ></div>
     <span class="font-weight-bold score"><%=post.score%></span>
      <div class ="fa fa-arrow-down downvote <%= is_downvoted post%> "></div>
      </div>
      </div>
<div class="col-11 ">
 <small><%= link_to post.community.name, community_path(post.community) %> | Posted by <%= link_to post.account.username, profile_path(post.account.username) %> <%= time_ago_in_words post.created_at%> ago. </small>
      <h4> <%= link_to  post.title, community_post_path(post.community_id, post) %> </h4>
       <p><%= truncate post.body, length: 200 %></p>

      </div>


      
       </div>
       </div>
    <% end %>

app/views/posts/edit.html.erb
<h2>Edit Post </h2>

<%= render partial: "form"%>

app/views/posts/new.html.erb
<h2>New Post </h2>

<%= render partial: "form"%>

app/views/posts/show.html.erb
<div class="card p-3">
    <div class="row">
      <div class="col-1 text-center">
      <div id="vote-actions-<%=@post.id%>" class="vote" data-id="<%=@post.id%>">
      <div class ="fa fa-arrow-up upvote <%= is_upvoted @post%>" ></div>
     <span class="font-weight-bold score"><%=@post.score%></span>
      <div class ="fa fa-arrow-down downvote <%= is_downvoted @post%> "></div>
      </div>
      </div>
      <div class="col-11">
<h2><%= @post.title %> </h2>


<%= simple_format @post.body%>

<br    />

<h6>Comment as <%= link_to current_account.username%></h6>
<%= form_for @comment, remote: true do |f| %>
  <%=f.hidden_field :post_id, value: @post.id%>
  <%=f.text_area :message, placeholder: "Your comment goes here", class: "form-control" %>

  <%=f.submit "Submit comment", class: "btn btn-success mt-3"%>


<% end %>

<div id="post_comments">
<%=render partial: "posts/comments", locals: {comments: @post.comments } %>
</div>




</div>