config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile
  
  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post "post/vote"  => "votes#create"

  root to: "public#index"
end

app/models/community.rb
class Community < ApplicationRecord
    belongs_to :account
    validates_presence_of :url, :name, :rules 
  
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :account
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_community, only: [:show]


    def index
        @communities = Community.all
    end

    def show
        @posts = @community.posts.limit(20).sort_by{|p| p.score}.reverse
        @subscriber_count = @community.subscribers.count
        @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
        @subscription = Subscription.new
    end

    def new 
        @community = Community.new
    end

    def create 
        @community = Community.new community_values
        @community.account_id = current_account.id

        if @community.save
            redirect_to communities_path
        else
            render :new
        end
    end

    private

    def set_community
        @community = Community.find(params[:id])
    end

    def community_values
        params.require(:community).permit(:name, :url, :summary, :rules)
    end


end

app/views/communities/_form.html.erb
<div class="row">
<div class="col-sm-6">

<%= form_for @community do |form| %>
<div class="form-group">
<%= label_tag :name %>
<%= form.text_field :name, class: "form-control"%>
</div>

<div class="form-group">
<%= label_tag :url %>
<%= form.text_field :url, class: "form-control"%>
</div>

<div class="form-group">
<%= label_tag :rules %>
<%= form.text_area :rules, class: "form-control"%>
</div>

<div class="form-group">
<%= label_tag :summary %>
<%= form.text_field :summary, class: "form-control"%>
</div>

<%= form.submit "Submit", class: "btn btn-primary"%>
<% end %>
</div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f|%>

<%=f.hidden_field :community_id, value: community_id%>
<%= f.submit "Join Subreddit", class: "btn btn-success text-uppercase center"%>


<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %> 
<div class="float-right">
    <%= link_to "Create new Community", new_community_path, class: "btn btn-outline-primary"%>
</div>
<% end %>



<% if @communities.size > 0 %>
    <% @communities.each do |community| %>
  
      <div class="card">
        <h3><%= link_to community.name, community %></h3>
        <%= simple_format community.rules %>
      </div>
   <% end %> 
<% else %>
<p>No communities to display.</p>

<% end %>

app/views/communities/new.html.erb
<h2>New Community </h2>

<%= render partial: "form"%>

app/views/communities/show.html.erb
<h2><%= @community.name %></h2>

<span class="row mb-4">
  <span class="col-sm-8">

  

 <%= render partial: "posts/list", locals: {posts: @posts}%>



</span>
<span class="col-sm-4">
<span class="card p-3">
<h5>About this community </h5>
<p class="mt-2"><%= @community.summary%></p>

<p><%=pluralize @subscriber_count, "Member"%>  </p>
<% if @is_subscribed %>
<%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-right" %>
<%else%>
<%=render partial: "communities/subscribe", locals: { community_id: @community.id }%>

<% end %>

</span>
<br  />
<span class="card p-3">
<small class="pt-3"> <h5>Rules:</h5> <p>
<%= simple_format @community.rules %> </p>
</small>
</span>
</span>
</span>