config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile
  
  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post "post/vote"  => "votes#create"

  root to: "public#index"
end

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm  navbar-dark">
    <div class="col-12 pt-0 pb-1  ">
      <p class="h3"><%= link_to "Reddit klon", root_path %>
      <span class="float-right">
      <% if account_signed_in? %>
      
      <small><span class="fa fa-star text-warning"><%=current_account.karma%>  </span></small>
      
      <span class="dropdown float-right">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_account.username%>
  </a>

  <span class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
    
    <%= link_to "Profile", profile_path(current_account.username), class: "dropdown-item" %>
    <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
    <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
  </span>
</span>
        
      <% else %>
        <%= link_to 'Log in', new_account_session_path, class: "btn btn-outline-primary" %>
        <%= link_to 'Sign Up', new_account_registration_path, class: "btn btn-primary" %>
      <% end %>
      </span></p>
      
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Klon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'%>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
<section class= "bg-light">
    <div class="container">
       <div class="row">
        <div class="col-sm-12 pt-4 pb-5">
       
       
        <%= yield %>
       
       
        </div>
</div>
</section>

    <%= render partial: "layouts/footer" %>
  </body>
</html>